### ISSUE TITLE
Nepy dependecy

### ISSUE THREAD

**Issue by PascalLike** [emotional-cities/pluma-analysis#13]
The `nepy` dependency (https://github.com/emotional-cities/pluma-analysis/blob/main/environment.yml#L12) is unavailable on default conda repos.

I was trying the procedure here https://github.com/emotional-cities/pluma-analysis#how-to-build, and it failed during the env creation step in Visual Studio.

**Comment by bruno-f-cruz** [comment]
Ya, it should be added via pip:
`pip install nepy`

**Comment by PascalLike** [comment]
Thanks for the quick feedback! Github Actions are a great way to test that dependencies are all listed correctly. If you have time, take a look.
